Controllers/DishController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using asp_projekt.Data;
using asp_projekt.Models;
using Microsoft.AspNetCore.Authorization;

namespace asp_projekt.Controllers
{
    public class DishController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DishController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Dish
        public async Task<IActionResult> Index()
        {
            return View(await _context.Dish.ToListAsync());
        }


        // Partial som hanterar live-sökning via AJAX
        public PartialViewResult Ajax(string searchString)
        {
            List<Dish> dishes;

            if (!String.IsNullOrEmpty(searchString))
            {
                dishes = _context.Dish.Where(s => s.Name.Contains(searchString)
                                       || s.Description.Contains(searchString)).ToList();
            }
            else
            {
                dishes = _context.Dish.ToList();
            }
            return PartialView("_DishPartial", dishes);
        }


        // GET: Dish/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dish = await _context.Dish
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dish == null)
            {
                return NotFound();
            }

            return View(dish);
        }

        // GET: Dish/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Dish/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,Type,Name,Description,Price")] Dish dish)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dish);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dish);
        }

        // GET: Dish/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dish = await _context.Dish.FindAsync(id);
            if (dish == null)
            {
                return NotFound();
            }
            return View(dish);
        }

        // POST: Dish/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Type,Name,Description,Price")] Dish dish)
        {
            if (id != dish.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dish);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DishExists(dish.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dish);
        }

        // GET: Dish/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dish = await _context.Dish
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dish == null)
            {
                return NotFound();
            }

            return View(dish);
        }

        // POST: Dish/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dish = await _context.Dish.FindAsync(id);
            _context.Dish.Remove(dish);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DishExists(int id)
        {
            return _context.Dish.Any(e => e.Id == id);
        }
    }
}

Controllers/DrinkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using asp_projekt.Data;
using asp_projekt.Models;
using Microsoft.AspNetCore.Authorization;

namespace asp_projekt.Controllers
{
    public class DrinkController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DrinkController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Drink
        public async Task<IActionResult> Index()
        {
            return View(await _context.Drink.ToListAsync());
        }


        // Partial som hanterar live-sökning via AJAX
        public PartialViewResult Ajax(string searchString)
        {
            List<Drink> drinks;

            if (!String.IsNullOrEmpty(searchString))
            {
                drinks = _context.Drink.Where(s => s.Name.Contains(searchString)
                                       || s.Description.Contains(searchString)).ToList();
            }
            else
            {
                drinks = _context.Drink.ToList();
            }
            return PartialView("_DrinkPartial", drinks);
        }


        // GET: Drink/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var drink = await _context.Drink
                .FirstOrDefaultAsync(m => m.Id == id);
            if (drink == null)
            {
                return NotFound();
            }

            return View(drink);
        }

        // GET: Drink/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Drink/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,Type,Name,Description,Price")] Drink drink)
        {
            if (ModelState.IsValid)
            {
                _context.Add(drink);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(drink);
        }

        // GET: Drink/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var drink = await _context.Drink.FindAsync(id);
            if (drink == null)
            {
                return NotFound();
            }
            return View(drink);
        }

        // POST: Drink/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Type,Name,Description,Price")] Drink drink)
        {
            if (id != drink.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(drink);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DrinkExists(drink.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(drink);
        }

        // GET: Drink/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var drink = await _context.Drink
                .FirstOrDefaultAsync(m => m.Id == id);
            if (drink == null)
            {
                return NotFound();
            }

            return View(drink);
        }

        // POST: Drink/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var drink = await _context.Drink.FindAsync(id);
            _context.Drink.Remove(drink);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DrinkExists(int id)
        {
            return _context.Drink.Any(e => e.Id == id);
        }
    }
}

Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using asp_projekt.Data;
using asp_projekt.Models;
using Microsoft.AspNetCore.Authorization;

namespace asp_projekt.Controllers
{
    public class RoomController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RoomController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Room
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Room.ToListAsync());
        }

        // GET: Room/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Room
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // GET: Room/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Room/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,RoomName,NoOfRooms,PricePerNight,MaxNoOfPersons,SquareMeter,BedWidth,View,BreakFast")] Room room)
        {
            if (ModelState.IsValid)
            {
                _context.Add(room);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        // GET: Room/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Room.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            return View(room);
        }

        // POST: Room/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,RoomName,NoOfRooms,PricePerNight,MaxNoOfPersons,SquareMeter,BedWidth,View,BreakFast")] Room room)
        {
            if (id != room.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        // GET: Room/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Room
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Room/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var room = await _context.Room.FindAsync(id);
            _context.Room.Remove(room);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomExists(int id)
        {
            return _context.Room.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_DishPartial.cshtml
@model IEnumerable<asp_projekt.Models.Dish>

@if (Model.Count() == 0)
{
    <h4>Inga bokningar hittade</h4>
}
else
{
    <div class="responsive-table">
        <table class="table" id="dish-table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Type)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Price)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Type)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Price)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id">Redigera</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Information</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Radera</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        </div>
        }

Views/Shared/_DrinkPartial.cshtml
@model IEnumerable<asp_projekt.Models.Drink>

@if (Model.Count() == 0)
{
    <h4>Inga bokningar hittade</h4>
}
else
{
    <div class="responsive-table">
        <table class="table" id="drink-table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Type)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Price)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Type)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Price)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id">Redigera</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Information</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Radera</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        </div>
        }

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"] - Pelican Palace</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Google Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Anton%7CHeebo%7CMukta%7CRighteous%7CTeko%7CTrade+Winds&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <!--Huvudmeny -->
    <header id="main-header" class="z-depth-1">
        <nav class="nav-wraper">
            <!-- <div class="container">-->
            <a class="brand-logo black-text" asp-area="" asp-controller="Home" asp-action="Index">Pelican Palace</a>
            <a href="#" class="sidenav-trigger hide-on-lar" data-target="mobile-links">
                <i class="material-icons black-text">menu</i>
            </a>

            <ul class="right hide-on-med-and-down">
                @if (!SignInManager.IsSignedIn(User))
                {
                    <li class="nav-item">
                        <a class="black-text" asp-area="" asp-controller="Home" asp-action="Index">Startsidan</a>
                    </li>
                    <li class="nav-item">
                        <a class="black-text" asp-area="" asp-controller="Home" asp-action="Hotel">Hotellet</a>
                    </li>
                    <li class="nav-item">
                        <a class="black-text" asp-area="" asp-controller="Home" asp-action="Restaurant">Restaurangen</a>
                    </li>
                    <li class="nav-item">
                        <a class="black-text" asp-area="" asp-controller="Home" asp-action="Contact">Kontakt</a>
                    </li>
                    <li>
                        <a asp-area="Identity" asp-page="/Account/Login">
                            <i class="material-icons orange-text login-i">account_circle</i>
                        </a>
                    </li>

                }
                else
                {
                    <li class="nav-item">
                        <a class="black-text" asp-area="" asp-controller="Home" asp-action="Index">Startsidan</a>
                    </li>
                    <li class="nav-item">
                        <a class="black-text" asp-area="" asp-controller="Home" asp-action="Hotel">Hotellet</a>
                    </li>
                    <li class="nav-item">
                        <a class="black-text" asp-area="" asp-controller="Home" asp-action="Restaurant">Restaurangen</a>
                    </li>
                    <li>
                        <a asp-area="Identity" asp-page="/Account/Manage/Index">
                            <i class="material-icons green-text login-i">account_circle</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <button type="submit" class="nav-link btn orange text-dark">Logga ut</button>
                        </form>
                    </li>
                }

                <!--<partial name="_LoginPartial" />-->

            </ul>
            <!--</div>-->
        </nav>
    </header>
    <!--Slut på uvudmeny -->
    <!-- Administration-->
    @if (SignInManager.IsSignedIn(User))
    {
        <div id="admin-panel">

            <div>
                <a asp-area="" asp-controller="HotelBooking" asp-action="Index">Hotellbokningar</a>
            </div>

            <div>
                <a asp-area="" asp-controller="RestaurantBooking" asp-action="Index">Bordsbokningar</a>
            </div>
            <div>
                <a asp-area="" asp-controller="Room" asp-action="Index">Rum</a>
            </div>
            <div>
                <a asp-area="" asp-controller="Dish" asp-action="Index">Mat</a>
            </div>
            <div>
                <a asp-area="" asp-controller="Drink" asp-action="Index">Dryck</a>
            </div>
        </div>
    }
    <!-- Administration-->
    <!--Mobilmeny -->
    <ul class="sidenav" id="mobile-links">
        @if (!SignInManager.IsSignedIn(User))
        {
            <li class="nav-item">
                <a class="black-text" asp-area="" asp-controller="Home" asp-action="Index">Startsidan</a>
            </li>
            <li class="nav-item">
                <a class="black-text" asp-area="" asp-controller="Home" asp-action="Hotel">Hotellet</a>
            </li>
            <li class="nav-item">
                <a class="black-text" asp-area="" asp-controller="Home" asp-action="Restaurant">Restaurangen</a>
            </li>
            <li class="nav-item">
                <a class="black-text" asp-area="" asp-controller="Home" asp-action="Contact">Kontakt</a>
            </li>
            <li>
                <a asp-area="Identity" asp-page="/Account/Login">
                    <i class="material-icons orange-text login-i">account_circle</i>
                </a>
            </li>

        }
        else
        {
            <li class="nav-item">
                <a class="black-text" asp-area="" asp-controller="Home" asp-action="Index">Startsidan</a>
            </li>
            <li class="nav-item">
                <a class="black-text" asp-area="" asp-controller="Home" asp-action="Hotel">Hotellet</a>
            </li>
            <li class="nav-item">
                <a class="black-text" asp-area="" asp-controller="Home" asp-action="Restaurant">Restaurangen</a>
            </li>
            <li>
                <a asp-area="Identity" asp-page="/Account/Manage/Index">
                    <i class="material-icons green-text login-i">account_circle</i>
                </a>
            </li>
            <li class="nav-item">
                <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                    <button type="submit" class="btn orange">Logga ut</button>
                </form>
            </li>
        }
    </ul>
    <!-- Slut på mobilmenyn-->



    <div class="content">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--Sidfot-->
    <footer class="page-footer">
        <div class="container">
            <div class="row">
                <div class="col s12 l8">
                    <h5>Om sidan</h5>
                    <p>
                        It was popularised in the 1960s with the release of
                        Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing
                        software like Aldus PageMaker including versions of Lorem Ipsum
                    </p>
                    <div class="row">

                        <div class="col s3 l3 center">
                            <h6>Bokningar</h6>
                            <div class="counter" data-target="50">0</div>
                        </div>

                        <div class="col s3 l3 center">
                            <h6>Antal rum</h6>
                            <div class="counter" data-target="144">0</div>
                        </div>

                        <div class="col s3 l3 center">
                            <h6>Likes</h6>
                            <div class="counter" data-target="220">0</div>
                        </div>

                        <div class="col s3 l3 center">
                            <h6>Anställda</h6>
                            <div class="counter" data-target="32">0</div>
                        </div>

                    </div>
                </div>
                <div class="col s12 l2 offset-l2">
                    <h5>Länkar</h5>
                    <ul>
                        <li><a href="#">Facebook</a></li>
                        <li><a href="#">Instagram</a></li>
                        <li><a href="#">Youtube</a></li>
                    </ul>
                    <!--Knapp för modal-->
                    <a href="#info" class="modal-trigger">Villkor</a>
                </div>
            </div>
        </div>
        <!--Nedre sidfoten-->
        <div class="footer-copyright">
            <div class="container center-align">
                <p>&copy; Pelican Palace 2020</p>
            </div>
        </div>
        <!--SLut på nedre sidfot-->
    </footer>
    <!-- Slut på sidfot -->
    <!--Modal-->
    <div class="container">
        <div class="modal" id="info">
            <div class="modal-content">
                <h4>Information</h4>
                <p>
                    It has survived not only five centuries, but also the leap into electronic typesetting,
                    remaining essentially unchanged. It was popularised in the 1960s with the release of
                    Letraset sheets containing Lorem Ipsum passages, and more recently with desktop
                </p>
            </div>
            <div class="modal-footer">
                <a href="#contact-section" class="modal-close btn orange waves-light">
                    Acceptera och
                    stäng
                </a>
            </div>
        </div>
    </div>
    <!--Slut på modal-->

    <!--Ändring av färgschema-->
    <div id="theme-changer">
        <input type="checkbox" id="theme-box" />
        <label for="theme-box" id="theme-label">
            <span id="ball"></span>
        </label>
    </div>
    <!--Ändring av färgschema-->

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!--
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        -->
    @RenderSection("Scripts", required: false)

</body>
</html>