Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using asp_projekt.Models;
using Microsoft.AspNetCore.Authorization;
using asp_projekt.Data;
using Microsoft.EntityFrameworkCore;

namespace asp_projekt.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly ApplicationDbContext _context;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Hotel()
        {
            return View();
        }

       
        // Uppdaterad för att generera listor med maträtter och dricka
        public ActionResult Restaurant()
        {
            ViewModel mymodel = new ViewModel();
            mymodel.Dish = _context.Dish.ToList();
            mymodel.Drink = _context.Drink.ToList();
            return View(mymodel);
        }

        public IActionResult Contact()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HotelBookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using asp_projekt.Data;
using asp_projekt.Models;
using Microsoft.AspNetCore.Authorization;
// Mail
using MailKit.Net.Smtp;
using MailKit;
using MimeKit;
using MimeKit.Text;
using Microsoft.AspNetCore.Http;

namespace asp_projekt.Controllers
{
    public class HotelBookingController : Controller
    {

        private readonly ApplicationDbContext _context;

        public HotelBookingController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: HotelBooking
        [Authorize]
        public async Task<IActionResult> Index(string sortOrder)
        {
            var applicationDbContext = _context.HotelBooking.Include(h => h.Room);

            // Sortering
            ViewData["CheckInParm"] = String.IsNullOrEmpty(sortOrder) ? "checkin_desc" : "";
            ViewData["EmailParm"] = sortOrder == "Email" ? "email_desc" : "Email";

            var hotelBookings = from h in _context.HotelBooking.Include(r => r.Room)
                                select h;

            switch (sortOrder)
            {
                case "email_desc":
                    hotelBookings = hotelBookings.OrderByDescending(h => h.Email);
                    break;
                case "Email":
                    hotelBookings = hotelBookings.OrderBy(h => h.Email);
                    break;
                case "checkin_desc":
                    hotelBookings = hotelBookings.OrderByDescending(h => h.CheckIn);
                    break;
                default:
                    hotelBookings = hotelBookings.OrderBy(h => h.CheckIn);
                    break;
            }
            return View(await hotelBookings.AsNoTracking().ToListAsync());
        }

        // Partial som hanterar live-sökning via AJAX
        public PartialViewResult Ajax(string searchString)
        {
            List<HotelBooking> hotelBookings;

            if (!String.IsNullOrEmpty(searchString))
            {
                hotelBookings = _context.HotelBooking.Where(s => s.Email.Contains(searchString)
                                       || s.FirstName.Contains(searchString)
                                       || s.LastName.Contains(searchString)).ToList();
            } else
            {
                hotelBookings = _context.HotelBooking.ToList();
            }
            return PartialView("_HotelBookingPartial", hotelBookings);
        }

        // GET: HotelBooking/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotelBooking = await _context.HotelBooking
                .Include(h => h.Room)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hotelBooking == null)
            {
                return NotFound();
            }

            return View(hotelBooking);
        }

        // GET: HotelBooking/Create
        public IActionResult Create()
        {
            ViewData["RoomId"] = new SelectList(_context.Room, "Id", "RoomName");
            return View();
        }

        // POST: HotelBooking/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CheckIn,CheckOut,NoOfPersons,RoomId,FirstName,LastName,PhoneNumber,Email,ExtraInformation")] HotelBooking hotelBooking)
        {
            if (ModelState.IsValid)
            {
                _context.Add(hotelBooking);
                await _context.SaveChangesAsync();

                // Lägger bokningsinfon i variabler
                var customerName = hotelBooking.FirstName + " " + hotelBooking.LastName;
                var customerEmail = hotelBooking.Email;
                var customerCheckIn = hotelBooking.CheckIn.ToString("d");
                var customerCheckOut = hotelBooking.CheckOut.ToString("d");
                var customerNoOfPersons = hotelBooking.NoOfPersons;
                //var customerExtraInfo = restaurantBooking.ExtraInformation;

                // Hämtar namnet på rummet efter rumID
                var query =
                   from c in _context.Room
                   where c.Id == hotelBooking.RoomId
                   select c;

                var customerRoom = "";
                // Sätter rumsnamnet
                foreach (var c in query)
                {
                    customerRoom = c.RoomName;
                }

                // Mail
                var message = new MimeMessage();
                message.From.Add(new MailboxAddress("Pelican Palace", "pelicanpalace.ab@gmail.com"));
                message.To.Add(new MailboxAddress(customerName, customerEmail));
                message.Subject = "Bokningsbekräftelse";
                message.Body = new TextPart(TextFormat.Html)
                {
                    Text = "<h1> Hej, " + customerName + " </h1 >" +
                    "<p>Tack för att du bokar din hotellvistelse på Pelican Palace!</p>" +
                    "<p>Information om din bokning finner du nedan</p>" +
                    "<p>Datum för incheckning: " + customerCheckIn + "</p>" +
                    "<p>Datum för utcheckning: " + customerCheckOut + "</p>" +
                    "<p>Bokat rum: " + customerRoom + "</p>" +
                    "<p>Antal personer: " + customerNoOfPersons + "</ p >" +
                    "<h4>Välkomna! </h4>"
                };

                // Konfigurering av email
                using (var client = new SmtpClient())
                {
                    client.ServerCertificateValidationCallback = (s, c, h, e) => true;
                    client.Connect("smtp.gmail.com", 587, false);
                    client.Authenticate("pelicanpalace.ab@gmail.com", "password");
                    client.Send(message);
                    client.Disconnect(true);
                };

                //Skapar sessionsvariabler för att skicka bokningsinfo till bokningsbekräftelsen
                HttpContext.Session.SetString("customer-name", customerName);

                return RedirectToAction(nameof(BookingConfirmation));
                //return View("BookingConfirmation", hotelBooking);
            }
            ViewData["RoomId"] = new SelectList(_context.Room, "Id", "RoomName", hotelBooking.RoomId);
            return View(hotelBooking);
        }


        // Bokningsbekräftelse
        public IActionResult BookingConfirmation()
        {
            // Hämtar sessionsvariabeln med bokningsnamnet
            string sess = HttpContext.Session.GetString("customer-name");
            // Sparar i viewbag
            ViewBag.CustomerName = sess;

            return View();
        }



        // GET: HotelBooking/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotelBooking = await _context.HotelBooking.FindAsync(id);
            if (hotelBooking == null)
            {
                return NotFound();
            }
            ViewData["RoomId"] = new SelectList(_context.Room, "Id", "RoomName", hotelBooking.RoomId);
            return View(hotelBooking);
        }

        // POST: HotelBooking/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CheckIn,CheckOut,NoOfPersons,RoomId,FirstName,LastName,PhoneNumber,Email,ExtraInformation")] HotelBooking hotelBooking)
        {
            if (id != hotelBooking.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hotelBooking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HotelBookingExists(hotelBooking.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoomId"] = new SelectList(_context.Room, "Id", "RoomName", hotelBooking.RoomId);
            return View(hotelBooking);
        }

        // GET: HotelBooking/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotelBooking = await _context.HotelBooking
                .Include(h => h.Room)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hotelBooking == null)
            {
                return NotFound();
            }

            return View(hotelBooking);
        }

        // POST: HotelBooking/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]

Views/Home/Contact.cshtml

@{
    ViewData["Title"] = "Kontakt";
}

<!-- Stor bild-->
<div class="banner" id="contact-banner"></div>
<!-- Slut på stor bild-->

<div class="container full-height">
    <!--Kontakt-sektionen-->
    <section class="big-section scrollspy" id="contact">
        <div class="container">
            <div class="row">
                <div class="col s12 l5">
                    <h3>Kontakta oss</h3>
                    <p> Bäverbacken 321 </p>
                    <p> 127 44 Skärholmen </p>
                    <p> Öppet 24/7 </p>
                    <p>
                        It has survived not only five centuries, but also the leap into electronic typesetting,
                        remaining essentially unchanged. It was popularised in the 1960s with the release of
                        Letraset sheets containing Lorem
                    </p>

                </div>


                <!--Kontaktformulär-->
                <div class="col s12 l5 offset-l2" id="contact-form">
                    <form action="#">
                        <div class="input-field">
                            <i class="material-icons prefix">person</i>
                            <input type="text" id="name">
                            <label for="name">Ditt namn</label>
                        </div>
                        <div class="input-field">
                            <i class="material-icons prefix">email</i>
                            <input type="text" id="email">
                            <label for="email">Din e-post</label>
                        </div>
                        <div class="input-field">
                            <i class="material-icons prefix">message</i>
                            <textarea name="message" id="message" class="materialize-textarea"></textarea>
                            <label for="message">Ditt meddelande</label>
                        </div>
                        <div class="input-field center">
                            <p>Vill du bli kontaktad via telefon?</p>
                            <p>
                                <label>
                                    <input type="checkbox">
                                    <span>Ja</span>
                                </label>
                            </p>
                        </div>
                        <div class="input-field right">
                            <button class="btn orange">Skicka</button>
                        </div>
                    </form>
                </div>
                <!--Slut på kontaktformulär-->
            </div>
        </div>
    </section>
    <!--Slut på kontakt-sektionen-->

</div>

Views/Home/Hotel.cshtml

@{
    ViewData["Title"] = "Hotellet";
}

<!-- Stor bild-->
<div class="banner" id="hotel-banner"></div>
<!-- Slut på stor bild-->


<div class="container full-height">
    <h2>Hotellet</h2>
    <p>
        It has survived not only five centuries, but also the leap into electronic typesetting,
        remaining essentially unchanged. It was popularised in the 1960s with the release of
        Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing
        software like Aldus PageMaker including versions of Lorem Ipsum.
    </p>

    <div class="booking-link-div">
        <a class="orange-text booking-link" asp-area="" asp-controller="HotelBooking" asp-action="Create">Boka hotellrum!</a>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Startsidan";
}

<!-- Stor bild-->
<div class="banner" id="index-banner"></div>
<!-- Slut på stor bild-->

<div class="container pitch">
    <div class="row">
        <h2 class="center orange-text" id="pitch-title">Pelican Palace Hotell & Restaurang </h2>
    </div>
</div>


<!--Hotellet -->
<section class="big-section scrollspy" id="hotel">
    <div class="container">
        <div class="row">
            <div class="col s12 l10 offset-l1">
                <h3>Hotellet</h3>
                <p>
                    It has survived not only five centuries, but also the leap into electronic typesetting,
                    remaining essentially unchanged. It was popularised in the 1960s with the release of
                    Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing
                    software like Aldus PageMaker including versions of Lorem Ipsum
                </p>
            </div>
        </div>
    </div>
</section>

<!-- Sektion-->
<section class="big-section scrollspy">
    <div class="container">
        <div class="row">

            <div class="col s12 l4 m10 offset-m1">
                <div class="card hoverable">
                    <div class="card-image">
                        <img src="~/images/doubleroom.jpg" alt="Double room" class="materialboxed">
                        <a asp-area="" asp-controller="HotelBooking" asp-action="Create" class="halfway-fab btn-floating orange">
                            <i class="material-icons">hotel</i>
                        </a>
                    </div>
                    <div class="card-content">
                        <span class="card-title">Dubbelrum</span>
                        <p>
                            It has survived not only five centuries, but also the leap into electronic typesetting,
                            remaining essentially unchanged.
                        </p>
                    </div>
                    <div class="card-action">
                        <a asp-area="" asp-controller="Home" asp-action="Hotel">Läs mer</a>
                        <a asp-area="" asp-controller="HotelBooking" asp-action="Create">Boka hotell</a>
                    </div>
                </div>
            </div>

            <div class="col s12 l4 m10 offset-m1">
                <div class="card hoverable">
                    <div class="card-image">
                        <img src="~/images/superiorroom.jpg" alt="Double room superior" class="materialboxed">
                        <a asp-area="" asp-controller="HotelBooking" asp-action="Create" class="halfway-fab btn-floating orange">
                            <i class="material-icons">hotel</i>
                        </a>
                    </div>
                    <div class="card-content">
                        <span class="card-title">Dubbelrum Superior</span>
                        <p>
                            It has survived not only five centuries, but also the leap into electronic typesetting,
                            remaining essentially unchanged.
                        </p>
                    </div>
                    <div class="card-action">
                        <a asp-area="" asp-controller="Home" asp-action="Hotel">Läs mer</a>
                        <a asp-area="" asp-controller="HotelBooking" asp-action="Create">Boka hotell</a>
                    </div>
                </div>
            </div>

            <div class="col s12 l4 m10 offset-m1">
                <div class="card hoverable">
                    <div class="card-image">
                        <img src="~/images/singleroom.jpg" alt="Single room" class="materialboxed">
                        <a asp-area="" asp-controller="HotelBooking" asp-action="Create" class="halfway-fab btn-floating orange">
                            <i class="material-icons">hotel</i>
                        </a>
                    </div>
                    <div class="card-content">
                        <span class="card-title">Enkelrum</span>
                        <p>
                            It has survived not only five centuries, but also the leap into electronic typesetting,
                            remaining essentially unchanged.
                        </p>
                    </div>
                    <div class="card-action">
                        <a asp-area="" asp-controller="Home" asp-action="Hotel">Läs mer</a>
                        <a asp-area="" asp-controller="HotelBooking" asp-action="Create">Boka hotell</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- Slut på sektion-->
<!-- Sektion-->
<section class="big-section scrollspy" id="restaurant">
    <div class="container">
        <div class="row">
            <div class="col s12 l10 offset-l1" id="restaurant-info">
                <h3>Restaurangen</h3>
                <p>
                    It has survived not only five centuries, but also the leap into electronic typesetting,
                    remaining essentially unchanged. It was popularised in the 1960s with the release of
                    Letraset sheets containing.
                </p>
            </div>

            <div class="col s12 l6 m10 offset-m1">
                <div class="card hoverable">
                    <div class="card-image">
                        <img src="~/images/food.jpg" alt="Our food" class="materialboxed">
                        <a asp-area="" asp-controller="Home" asp-action="Restaurant" class="halfway-fab btn-floating orange">
                            <i class="material-icons">local_dining</i>
                        </a>
                    </div>
                    <div class="card-content">
                        <span class="card-title">Äta</span>
                        <p>
                            It has survived not only five centuries, but also the leap into electronic typesetting,
                            remaining essentially unchanged.
                        </p>
                    </div>
                    <div class="card-action">
                        <a asp-area="" asp-controller="Home" asp-action="Restaurant">Läs mer</a>
                        <a asp-area="" asp-controller="RestaurantBooking" asp-action="Create">Boka bord</a>
                    </div>
                </div>
            </div>

            <div class="col s12 l6 m10 offset-m1">
                <div class="card hoverable">
                    <div class="card-image">
                        <img src="~/images/wine.jpg" alt="Our drinks" class="materialboxed">
                        <a asp-area="" asp-controller="Home" asp-action="Restaurant" class="halfway-fab btn-floating orange">
                            <i class="material-icons">local_dining</i>
                        </a>
                    </div>
                    <div class="card-content">
                        <span class="card-title">Dricka</span>
                        <p>
                            It has survived not only five centuries, but also the leap into electronic typesetting,
                            remaining essentially unchanged.
                        </p>
                    </div>
                    <div class="card-action">
                        <a asp-area="" asp-controller="Home" asp-action="Restaurant">Läs mer</a>
                        <a asp-area="" asp-controller="RestaurantBooking" asp-action="Create">Boka bord</a>
                    </div>
                </div>
            </div>



        </div>
    </div>
</section>
<!-- Slut på sektion-->
<!-- Parallax-->
<div class="parallax-container parallax-bottom">
    <div class="parallax"><img src="~/images/parallax3.jpg" class="responsive-img z-depth-1" alt="Our restaurant"></div>
</div>
<!-- Slut på parallax-->
<!--Kontakt-sektionen-->
<section class="big-section scrollspy" id="contact">
    <div class="container">
        <div class="row">
            <div class="col s12 l5">
                <h3>Kontakta oss</h3>
                <p>
                    It has survived not only five centuries, but also the leap into electronic typesetting,
                    remaining essentially unchanged. It was popularised in the 1960s with the release of
                    Letraset sheets containing Lorem
                </p>
                <p>
                    It has survived not only five centuries, but also the leap into electronic typesetting,
                    remaining essentially unchanged. It was popularised in the 1960s with the release of
                    Letraset sheets containing Lorem
                </p>

            </div>


            <!--Kontaktformulär-->
            <div class="col s12 l5 offset-l2" id="contact-form">
                <form action="#">
                    <div class="input-field">
                        <i class="material-icons prefix">person</i>
                        <input type="text" id="name">
                        <label for="name">Ditt namn</label>
                    </div>
                    <div class="input-field">
                        <i class="material-icons prefix">email</i>
                        <input type="text" id="email">
                        <label for="email">Din e-post</label>
                    </div>
                    <div class="input-field">
                        <i class="material-icons prefix">message</i>
                        <textarea name="message" id="message" class="materialize-textarea"></textarea>
                        <label for="message">Ditt meddelande</label>
                    </div>
                    <div class="input-field center">
                        <p>Vill du bli kontaktad via telefon?</p>
                        <p>
                            <label>
                                <input type="checkbox">
                                <span>Ja</span>
                            </label>
                        </p>
                    </div>
                    <div class="input-field right">
                        <button class="btn orange">Skicka</button>
                    </div>
                </form>
            </div>
            <!--Slut på kontaktformulär-->
        </div>
    </div>
</section>
<!--Slut på kontakt-sektionen-->